// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfrCQorKlkeu2xvG_Ww4DRjY4YmQoNzhA',
    appId: '1:116665276335:web:9a26cc9c2969e34f1f415a',
    messagingSenderId: '116665276335',
    projectId: 'yz-app-jam',
    authDomain: 'yz-app-jam.firebaseapp.com',
    storageBucket: 'yz-app-jam.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAt59xKE1V20pf1T8qbkJmItLm2YRvaK6Y',
    appId: '1:116665276335:android:0899e23fbd512eb31f415a',
    messagingSenderId: '116665276335',
    projectId: 'yz-app-jam',
    storageBucket: 'yz-app-jam.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC95nFcoGLZx1-9o9uSdc9lSVdjVDVRg-w',
    appId: '1:116665276335:ios:93481786f29ac7891f415a',
    messagingSenderId: '116665276335',
    projectId: 'yz-app-jam',
    storageBucket: 'yz-app-jam.appspot.com',
    iosBundleId: 'com.example.yzAppJam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC95nFcoGLZx1-9o9uSdc9lSVdjVDVRg-w',
    appId: '1:116665276335:ios:93481786f29ac7891f415a',
    messagingSenderId: '116665276335',
    projectId: 'yz-app-jam',
    storageBucket: 'yz-app-jam.appspot.com',
    iosBundleId: 'com.example.yzAppJam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfrCQorKlkeu2xvG_Ww4DRjY4YmQoNzhA',
    appId: '1:116665276335:web:ccce3d73ca25f7f71f415a',
    messagingSenderId: '116665276335',
    projectId: 'yz-app-jam',
    authDomain: 'yz-app-jam.firebaseapp.com',
    storageBucket: 'yz-app-jam.appspot.com',
  );
}
